version: '3'
services:
  postgresql:
     image: docker.io/postgres:14-alpine3.15
     env_file:
      - psql.env
     ports:
      - "5432:5432"
  mariadb:
    image: docker.io/mariadb:10.7
    env_file:
      - mariadb.env
    ports:
      - "3306:3306"
